# -*- coding: utf-8 -*-
"""stock markendipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThXqX77tF-X0VLo05vzfDzPm6Fz1f9yR
"""

import streamlit as st
import requests

st.set_page_config(page_title="📈 Stock Price Viewer", layout="centered")
st.title("📊 Real-Time Stock Price App")

API_KEY = "I0EOJY2NM6D1OFZJ"  # Your Alpha Vantage API Key

# --- Input Section ---
symbol = st.text_input("Enter Stock Symbol (e.g., AAPL, MSFT, TSLA)", "AAPL")

if st.button("🔍 Get Price"):
    url = f"https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol={symbol}&apikey={API_KEY}"

    try:
        response = requests.get(url)
        data = response.json()

        if "Global Quote" in data:
            quote = data["Global Quote"]
            st.subheader(f"💹 {quote['01. symbol']} Stock Info")
            st.write(f"🟢 **Price:** ${quote['05. price']}")
            st.write(f"📈 **Open:** ${quote['02. open']}")
            st.write(f"📉 **Low:** ${quote['04. low']}")
            st.write(f"📊 **Volume:** {quote['06. volume']}")
        else:
            st.error("⚠️ Invalid symbol or API limit reached. Try again later.")

    except Exception as e:
        st.error(f"Error: {e}")

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
